services:
  frontend:
    build: ./frontend
    container_name: forum_tntu_frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    command: npm run dev

  backend:
    image: forum_tntu:1.0.0
    build: ./forum_tntu
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - 8000:8000

  database:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    container_name: bd

volumes:
  postgres_data:
    name: forum_tntu_data
